#!/bin/bash
# These are useful, or at worst not harmful, for all images we build.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

zypper addrepo http://download.suse.de/ibs/SUSE:/SLE-12-SP3:/GA/standard/ SLE-12-SP3
zypper addrepo http://download.suse.de/ibs/SUSE:/SLE-12-SP3:/GA/images/repo/SLE-12-SP3-Server-POOL-x86_64-Media1/ SLE-12-SP3-Server-POOL
zypper addrepo http://download.suse.de/ibs/SUSE:/SLE-12-SP3:/GA/images/repo/SLE-12-SP3-SDK-POOL-x86_64-Media1/ SLE-12-SP3-SDK-POOL
