#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

SCRIPTDIR=$(dirname $0)
install -D -g root -o root -m 0644 ${SCRIPTDIR}/zypper-ref.service /usr/lib/systemd/system/zypper-ref.service
