#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

[ -n "$ARCH" ]
[ -n "$TARGET_ROOT" ]

if [ 'amd64' = "$ARCH" ] ; then
    ARCH="x86_64"
fi

DIB_CLOUD_IMAGES=http://clouddata.cloud.suse.de/images/${ARCH}/
BASE_IMAGE_FILE=SLES12-SP3.qcow2
BASE_IMAGE_TAR=${BASE_IMAGE_FILE//.qcow2}.${ARCH}.tgz
IMAGE_LOCATION=$DIB_CLOUD_IMAGES/$BASE_IMAGE_FILE
CACHED_IMAGE=$DIB_IMAGE_CACHE/$BASE_IMAGE_FILE
CACHED_TAR=$DIB_IMAGE_CACHE/$BASE_IMAGE_TAR

$TMP_HOOKS_PATH/bin/extract-image $BASE_IMAGE_FILE $BASE_IMAGE_TAR $IMAGE_LOCATION $CACHED_IMAGE
